spring:
  application:
    name: geulhyang

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/geulhyang
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # ??? ?? 'create', 'create-drop', 'validate' ? ??? ?????.
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL8Dialect ?? MySQL5Dialect

  kakao:
    client-id: e6cba8bdc76a3d72e7e3de193056c084
    client-secret: oL5wQvUGRcyKoXGmTBJY0zKlcnYGBLnf

  jwt:
    secret: eod31f98h91hf2kdla
    expiration: 1800000

